name: Deploy Nginx to KubeSail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up KubeConfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_DATA" > ~/.kube/config
          kubectl config view # Debugging: View the KubeConfig
          kubectl get nodes # Debugging: Verify connection to the cluster

      - name: Deploy Nginx
        run: |
          kubectl apply -f k8s/nginx-deployment.yaml
