name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: minikube start

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ~/.kube/config

      - name: Apply Kubernetes manifests
        run: kubectl apply -f nginx-deployment.yaml

      - name: Get Minikube IP
        run: |
          minikube ip
