name: Webots Simulation
on: [push]

jobs:
  test-robot:
    runs-on: ubuntu-latest
    container: cyberbotics/webots:latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile C Controller
        run: |
          cd controllers/ure_can_grasper
          make

      - name: Run Simulation
        run: |
          xvfb-run webots --batch --mode=fast --stdout --stderr worlds/ure.wbt
