name: Curl Nginx Container

on:
  push:
    branches:
      - main

jobs:
  curl-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a curl command
        run: |
          curl http://localhost:8080